checkInterval: 60  # In ticks (20 ticks = 1 second)
movementDistance: 2 # Amount of blocks a player needs to move to be counted as not afk
checksBeforeAfk: 100 # Amount of checks a person needs to not have moved enough to be AFK
enableAfkCommand: true

messages:
  prefix: '&9OpenAFK> &7'
  insufficientPermissions: '%openafk_prefix%Insufficient Permissions.'
  invalidUsage: '%openafk_prefix%Invalid Usage.'
  afkAreaSet: '%openafk_prefix%}AFK Area set successfully.'

detection:
  gamemodes:
    survival: true
    adventure: true
    creative: false # This will disable players from going afk if they are in this gamemode
    spectator: false

  fishing:
    enabled: true
    violationsNeeded: 5

    script:
      - "message|%openafk_prefix%AFK Fishing isn't allowed."
      - "setPlayerPitch|100"

  operatorsExempt: true # Players who have the permission openafk.exempt will also be exempt

scripts:
  onAfk:
    - "afkarea"
    - "message|&cNow AFK"
    - "title|&c&lAFK|&7See you soon!|10|10|999999999"
  onReturn:
    - "afkarea"
    - "message|&cNo longer AFK"
    - "title|&c&lAFK|&7See you soon!|10|10|0"
    - "title|&a&lWelcome Back!||10|10|20"

  onAfkCMD:
    - "afkarea"
    - "message|&bAFK by Command"
  onReturnCMD:
    - "afkarea"
    - "message|&bReturn by Command"

#actions:
#  broadcast:
#    enabled: true
#    needPermission: false # if this is enabled then only users with the permission openafk.announce will be able to see the broadcast
#
#    onAfk: true
#    message: '%openafk_prefix%%player_name% is AFK.'
#
#    onReturn: true
#    returnMessage: '%openafk_prefix%%player_name% is no longer AFK.'
#
#  afkArea: # Please set the afk zone with /openafk setafkarea
#    enabled: true
#
#  title:
#    enabled: true
#    message:
#      title: '&c&lAFK'
#      subtitle: '&7See you soon!'
#      fadeIn: 10
#      fadeOut: 10
#
#    returnMessage:
#      title: '&a&lWelcome Back!'
#      subtitle: ''
#      fadeIn: 10
#      fadeOut: 10
#      length: 40
#
#  message:
#    enabled: true
#    message: '%openafk_prefix%See you soon %player_name%!'
#    returnMessage: '%openafk_prefix%Welcome back %player_name%!'
#
#  actionbar:
#    enabled: true
#    message: "&9&lSee you soon!"
#    returnMessage: "&9Welcome back."