checkInterval: 60  # In ticks (20 ticks = 1 second)
movementDistance: 2 # Amount of blocks a player needs to move to be counted as not afk
checksBeforeAfk: 100 # Amount of checks a person needs to not have moved enough to be AFK
enableAfkCommand: true

messages:
  prefix: '&9OpenAFK> &7'
  insufficientPermissions: '%openafk_prefix%Insufficient Permissions.'
  invalidUsage: '%openafk_prefix%Invalid Usage.'
  afkAreaSet: '%openafk_prefix%}AFK Area set successfully.'

detection:
  gamemodes:
    survival: true
    adventure: true
    creative: false # This will disable players from going afk if they are in this gamemode
    spectator: false

  fishing:
    enabled: true
    violationsNeeded: 5

    enableSetPitch: true
    setPitch: 100
    violationMessage: "%openafk_prefix%AFK Fishing isn't allowed."

  operatorsExempt: true # Players who have the permission openafk.exempt will also be exempt

actions:
  broadcast:
    enabled: true
    needPermission: false # if this is enabled then only users with the permission openafk.announce will be able to see the broadcast

    onAfk: true
    message: '%openafk_prefix%%player_name% is AFK.'

    onReturn: true
    returnMessage: '%openafk_prefix%%player_name% is no longer AFK.'

  afkArea: # Please set the afk zone with /openafk setafkarea
    enabled: true

  title:
    enabled: true
    message:
      title: '&c&lAFK'
      subtitle: '&7See you soon!'
      fadeIn: 10
      fadeOut: 10

    returnMessage:
      title: '&a&lWelcome Back!'
      subtitle: ''
      fadeIn: 10
      fadeOut: 10
      length: 40

  message:
    enabled: true
    message: '%openafk_prefix%See you soon %player_name%!'
    returnMessage: '%openafk_prefix%Welcome back %player_name%!'

